# Generated by Django 5.2.5 on 2025-10-12 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(choices=[(1, 'Muito Ruim'), (2, 'Ruim'), (3, 'Regular'), (4, 'Bom'), (5, 'Muito Bom')])),
                ('datainicio', models.DateTimeField()),
                ('datafim', models.DateTimeField()),
                ('comentario', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
