# Generated by Django 5.2.5 on 2025-10-12 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('empresa', 'Empresa'), ('estudante', 'Estudante')], default=0, max_length=10),
            preserve_default=False,
        ),
    ]
